### ISSUE TITLE
Navigation broken

### ISSUE THREAD

**Issue by luisahorsten** [FelixHenninger/open-science-knowledge-base#10]
Hi Felix,
it seems to me that the navigation is somehow broken. Whenever I click an item in the navigation bar, the path to that item will just be added to the URL I'm currently on instead of navigating straight to that page. (This happens in Firefox.)
![grafik](https://user-images.githubusercontent.com/35098237/43912550-d7228dd6-9c02-11e8-97c6-c79e0dd3f4d8.png)

On my phone, I can't even open the navigation bar to begin with: When I hit the menu bar, nothing happens...

Sorry for my non-tech-savvy description, I hope you still understand what I mean :grimacing: 

Best, Luisa

**Comment by FelixHenninger** [comment]
Hej Luisa,

wow, thanks so much for pointing this out! Your description makes total sense, and I'm a bit embarrassed that I missed this (😬) -- I updated the theme without checking whether our customizations work (🙀). It should be fixed with 01a29883d400c572b20da8093b5b2bf797a59d91.

Best, and thanks again for noticing this and opening an issue!

-Felix
